name: test action for if
on:
  pull_request:
    types:
      - edited
    branches:
      - "test"

jobs:
  approved:
    if: github.event.closed.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
